version: "3.1"
services:
  database:
    restart: always
    image: postgres:13.2
    container_name: database
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - database_volume:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    expose:
      - "5433"
    networks:
      - back-end
  redis:
    image: redis
    container_name: redis
    ports:
      - "6378:6379"
    networks:
      - back-end
    expose:
      - "6378"
    volumes:
      - redis_volume:/data

  api:
    restart: always
    expose:
      - "8000"
    image: quantcollab-api
    container_name: api
    volumes:
      - backend_static_volume:/quantcollab-api/app/staticfiles/
    depends_on:
      - database
      - redis
    entrypoint:
      [
        "/bin/bash",
        "-c",
        "/quantcollab-api/docker/start_api.sh"
      ]
    stdin_open: true
    tty: true
    networks:
      - back-end
      - front-end
    environment:
      - DATABASE_URL=psql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:5432/${DATABASE_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - IEX_API_BASE_URL=${IEX_API_BASE_URL}
      - IEX_TOKEN=${IEX_TOKEN}
      - TRADIER_API_BASE_URL=${TRADIER_API_BASE_URL}
      - TRADIER_API_KEY=${TRADIER_API_KEY}
      - CELERY_BROKER_URL=redis://redis
      - CELERY_RESULT_BACKEND=redis://redis
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - FROM_EMAIL=${FROM_EMAIL}
      - FRONTEND_URL=${FRONTEND_URL}

  web:
    restart: always
    expose:
      - "81"
    image: collabinvest-web
    container_name: web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - backend_static_volume:/quantcollab-api/backend-static/
    networks:
      - back-end
      - front-end

    environment:
      - VIRTUAL_HOST=collabinvest.app
      - LETSENCRYPT_HOST=collabinvest.app
      - VIRTUAL_PORT=81
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/nginx.conf:/data/nginx/custom/http_top.conf
      - certs:/etc/nginx/certs
      - vhost-d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    environment:
      - DEFAULT_EMAIL=hesbonkiptoo5600@gmail.com
    networks:
      - back-end
      - front-end
  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost-d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=hesbonkiptoo5600@gmail.com
      - NGINX_PROXY_CONTAINER=nginx-proxy

networks:
  back-end:
  front-end:


volumes:
  certs:
  vhost-d:
  html:
  acme:
  backend_static_volume:
  database_volume:
  redis_volume:


